-- INSERT INTO PESSOAS(PESSOA_ID ,DATA_NASCIMENTO,PESSOA_NOME ) VALUES(1,'1988-05-16','tassio');
-- INSERT INTO PESSOAS(PESSOA_ID ,DATA_NASCIMENTO,PESSOA_NOME ) VALUES(2,'1988-05-16','tassio2');
-- INSERT INTO PESSOAS(PESSOA_ID ,DATA_NASCIMENTO,PESSOA_NOME ) VALUES(3,'1988-05-16','tassio3');
-- INSERT INTO PESSOAS(PESSOA_ID ,DATA_NASCIMENTO,PESSOA_NOME ) VALUES(4,'1988-05-16','tassio4');

-- INSERT INTO ENDERECOS VALUES(1,'4502820','conquista','rua nazare','A12',1);

-- UPDATE PESSOAS SET MAIN_ADRESS_ID = 1 WHERE PESSOA_ID = 1;